font=JetBrains Mono NF:size=17
terminal=ghostty -e
prompt="> "
layer=overlay
lines=15
width=60
dpi-aware=no
inner-pad=10
horizontal-pad=24
vertical-pad=18
match-counter=yes
include=/home/manok/.local/state/caelestia/theme/fuzzel.ini

# Caelestia's rounding.large and rounding.small
[border]
radius=25
selection-radius=12
width=0
