$lock = caelestia shell lock lock

general {
    lock_cmd = $lock
    before_sleep_cmd = $lock
    ignore_dbus_inhibit = false
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s && brightnessctl s 1%
    on-resume = brightnessctl -r
}

listener {
    timeout = 120
    on-timeout = $lock
}

listener {
    timeout = 300
    on-timeout = idle-suspend
}
