"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
format = """
$directory$git_branch$git_status$python$nodejs$cmd_duration
$character"""

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold blue"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "yellow"

[python]
format = "[$symbol$version( \\($virtualenv\\))]($style) "
symbol = " "
style = "green"
detect_extensions = []
detect_files = ["pyproject.toml", "requirements.txt", ".python-version", "Pipfile"]

[nodejs]
format = "[$symbol$version]($style) "
symbol = " "
style = "green"
detect_extensions = []
detect_files = ["package.json", ".node-version", ".nvmrc"]

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "dimmed white"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
