[General]
# Rewritten by bin/sddm-sync on every Caelestia scheme change.
Background=background.jpg
Font=JetBrainsMono Nerd Font
Mode=dark
TimeFormat=hh:mm
DateFormat=dddd, MMMM d

Primary=c2c1ff
OnPrimary=2a2a60
PrimaryContainer=7171ac
OnPrimaryContainer=ffffff
Surface=131317
OnSurface=e5e1e7
SurfaceContainer=201f23
SurfaceContainerHigh=2a292e
OnSurfaceVariant=c8c5d1
Outline=918f9a
OutlineVariant=47464f
Error=ffb4ab
